/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.g2.compu.diegohernandez;

/**
 *
 * @author Usuario
 */
public class jfrmcalc extends javax.swing.JFrame {
    
    //VARIABLE PUBLICA, GLOBAL Y GENERICA
    private String entrada = "";
    private double numero1, numero2, resultado;
    private String operador = "";
    
    

    /**
     * Creates new form jfrmcalc
     */
    public jfrmcalc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton12 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jtxtCantidad = new javax.swing.JTextField();
        btSIETE = new javax.swing.JButton();
        btOCHO = new javax.swing.JButton();
        btSEIS = new javax.swing.JButton();
        btDOS = new javax.swing.JButton();
        btCUATRO = new javax.swing.JButton();
        btUNO = new javax.swing.JButton();
        btCINCO = new javax.swing.JButton();
        btNUEVE = new javax.swing.JButton();
        btTRES = new javax.swing.JButton();
        btACE = new javax.swing.JButton();
        btMAS = new javax.swing.JButton();
        btMEN = new javax.swing.JButton();
        btIGUAL = new javax.swing.JButton();
        btPOR = new javax.swing.JButton();
        btCERO = new javax.swing.JButton();
        btDIV = new javax.swing.JButton();
        btC = new javax.swing.JButton();
        btRAIZ = new javax.swing.JButton();
        btPORCIENTO = new javax.swing.JButton();
        btPUNTO = new javax.swing.JButton();

        jButton12.setText("7");

        jButton16.setText("7");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jtxtCantidad.setText("0");
        jtxtCantidad.setEnabled(false);
        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });

        btSIETE.setText("7");
        btSIETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSIETEActionPerformed(evt);
            }
        });

        btOCHO.setText("8");
        btOCHO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOCHOActionPerformed(evt);
            }
        });

        btSEIS.setText("6");
        btSEIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSEISActionPerformed(evt);
            }
        });

        btDOS.setText("2");
        btDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDOSActionPerformed(evt);
            }
        });

        btCUATRO.setText("4");
        btCUATRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCUATROActionPerformed(evt);
            }
        });

        btUNO.setText("1");
        btUNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUNOActionPerformed(evt);
            }
        });

        btCINCO.setText("5");
        btCINCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCINCOActionPerformed(evt);
            }
        });

        btNUEVE.setText("9");
        btNUEVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNUEVEActionPerformed(evt);
            }
        });

        btTRES.setText("3");
        btTRES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTRESActionPerformed(evt);
            }
        });

        btACE.setText("AC");
        btACE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btACEActionPerformed(evt);
            }
        });

        btMAS.setText("+");
        btMAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMASActionPerformed(evt);
            }
        });

        btMEN.setText("-");
        btMEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMENActionPerformed(evt);
            }
        });

        btIGUAL.setText("=");
        btIGUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIGUALActionPerformed(evt);
            }
        });

        btPOR.setText("X");
        btPOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPORActionPerformed(evt);
            }
        });

        btCERO.setText("0");
        btCERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCEROActionPerformed(evt);
            }
        });

        btDIV.setText("/");
        btDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDIVActionPerformed(evt);
            }
        });

        btC.setText("C");
        btC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCActionPerformed(evt);
            }
        });

        btRAIZ.setText("√");
        btRAIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRAIZActionPerformed(evt);
            }
        });

        btPORCIENTO.setText("%");
        btPORCIENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPORCIENTOActionPerformed(evt);
            }
        });

        btPUNTO.setText(".");
        btPUNTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPUNTOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRAIZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPORCIENTO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPUNTO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSIETE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btOCHO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btNUEVE, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btACE, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btUNO, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(btPOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btDOS, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(btDIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btCERO, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btIGUAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(btMEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btSEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btMAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btTRES, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(jtxtCantidad)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSIETE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btOCHO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNUEVE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btACE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCUATRO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCINCO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSEIS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRAIZ, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUNO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTRES, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMEN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPORCIENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPOR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCERO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btIGUAL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPUNTO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSEISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSEISActionPerformed
        // TODO add your handling code here:
        entrada = entrada +6;
        jtxtCantidad.setText(entrada);
       
    }//GEN-LAST:event_btSEISActionPerformed

    private void btSIETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSIETEActionPerformed
        // TODO add your handling code here:
        entrada = entrada +7;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btSIETEActionPerformed

    private void btOCHOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOCHOActionPerformed
        // TODO add your handling code here:
        entrada = entrada + 8;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btOCHOActionPerformed

    private void btNUEVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNUEVEActionPerformed
        // TODO add your handling code here:
        entrada = entrada +9;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btNUEVEActionPerformed

    private void btCINCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCINCOActionPerformed
        // TODO add your handling code here:
        entrada = entrada +5;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btCINCOActionPerformed

    private void btCUATROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCUATROActionPerformed
        // TODO add your handling code here:
        entrada = entrada +4;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btCUATROActionPerformed

    private void btTRESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTRESActionPerformed
        // TODO add your handling code here:
        entrada = entrada +3;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btTRESActionPerformed

    private void btDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDOSActionPerformed
        // TODO add your handling code here:
        entrada = entrada +2;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btDOSActionPerformed

    private void btUNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUNOActionPerformed
        // TODO add your handling code here:
        entrada = entrada +1;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btUNOActionPerformed

    private void btCEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCEROActionPerformed
        // TODO add your handling code here:
        entrada = entrada +0;
        jtxtCantidad.setText(entrada);
        
    }//GEN-LAST:event_btCEROActionPerformed

    private void btMASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMASActionPerformed
        // TODO add your handling code here:
        //////CAPTURAR Y CONVERTIR TEXTO A VALOR
        jtxtCantidad.setText("");
        numero2 = Double.parseDouble(entrada);
        
            if (operador.equals("-")) {
            
            resultado = numero1 - numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("*")) {
            
            resultado = numero1 * numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("/")) {
            
            resultado = numero1 / numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            
        numero1 = Double.parseDouble(entrada);
        entrada = "";
        operador = "+";
        jtxtCantidad.setText(entrada);
        //////LIMPIAR CAJA TEXTO
        //////CAPTURAR EL SIGNO
        //////ENVIAR A PANTALLA
    }//GEN-LAST:event_btMASActionPerformed

    private void btMENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMENActionPerformed
        // TODO add your handling code here:
        
        jtxtCantidad.setText("");
        numero2 = Double.parseDouble(entrada);
        
            if (operador.equals("+")) {
            
            resultado = numero1 + numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("*")) {
            
            resultado = numero1 * numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("/")) {
            
            resultado = numero1 / numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }else{
        numero1 = Double.parseDouble(entrada);
        entrada = "";
        operador = "-";
        jtxtCantidad.setText(entrada);
            }
        
    }//GEN-LAST:event_btMENActionPerformed

    private void btDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDIVActionPerformed
        // TODO add your handling code here:
        jtxtCantidad.setText("");
        numero2 = Double.parseDouble(entrada);
        
            if (operador.equals("+")) {
            
            resultado = numero1 + numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("*")) {
            
            resultado = numero1 * numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("-")) {
            
            resultado = numero1 - numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
        
        numero1 = Double.parseDouble(entrada);
        entrada = "";
        operador = "/";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_btDIVActionPerformed

    private void btPORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPORActionPerformed
        // TODO add your handling code here:
        jtxtCantidad.setText("");
        numero2 = Double.parseDouble(entrada);
        
            if (operador.equals("+")) {
            
            resultado = numero1 + numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("-")) {
            
            resultado = numero1 - numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            if (operador.equals("/")) {
            
            resultado = numero1 / numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
            }
            
        numero1 = Double.parseDouble(entrada);
        entrada = "";
        operador = "*";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_btPORActionPerformed
 
    private void btIGUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIGUALActionPerformed
        // TODO add your handling code here:
        jtxtCantidad.setText("");
        numero2 = Double.parseDouble(entrada);
        
        
        if (operador.equals("%")) {
            resultado =  numero2 / 100;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada); 
        }   
        if (!operador.equals("&")){
        } else {
            resultado =  Math.sqrt(numero2);
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada); 
        }
        
        if (operador.equals("+")) {
          
            resultado = numero1 + numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        if (operador.equals("-")) {
            
            resultado = numero1 - numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        if (operador.equals("*")) {
          
            resultado = numero1 * numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        if (operador.equals("/")) {
            
            resultado = numero1 / numero2;
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        }
        
        
    }//GEN-LAST:event_btIGUALActionPerformed

    private void btACEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btACEActionPerformed
        // TODO add your handling code here:
        entrada = "";
        jtxtCantidad.setText(entrada);
        operador = "";
    }//GEN-LAST:event_btACEActionPerformed

    private void btCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCActionPerformed
        // TODO add your handling code here:
        
        String texto = jtxtCantidad.getText();
        if (texto.length() > 1){
            texto = texto.substring(0, texto.length() - 1);
            jtxtCantidad.setText(texto);
        }else {
            jtxtCantidad.setText("");
        }
        operador="";
    }//GEN-LAST:event_btCActionPerformed

    private void btRAIZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRAIZActionPerformed
        // TODO add your handling code here:
        
        
        entrada = "";
        operador = "&";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_btRAIZActionPerformed

    private void btPORCIENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPORCIENTOActionPerformed
        // TODO add your handling code here:
        
        entrada = "";
        operador = "%";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_btPORCIENTOActionPerformed

    private void btPUNTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPUNTOActionPerformed
        // TODO add your handling code here:
        if (!(entrada.contains("."))) {
            entrada = entrada + ".";
            jtxtCantidad.setText(entrada);
        }
    }//GEN-LAST:event_btPUNTOActionPerformed

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmcalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btACE;
    private javax.swing.JButton btC;
    private javax.swing.JButton btCERO;
    private javax.swing.JButton btCINCO;
    private javax.swing.JButton btCUATRO;
    private javax.swing.JButton btDIV;
    private javax.swing.JButton btDOS;
    private javax.swing.JButton btIGUAL;
    private javax.swing.JButton btMAS;
    private javax.swing.JButton btMEN;
    private javax.swing.JButton btNUEVE;
    private javax.swing.JButton btOCHO;
    private javax.swing.JButton btPOR;
    private javax.swing.JButton btPORCIENTO;
    private javax.swing.JButton btPUNTO;
    private javax.swing.JButton btRAIZ;
    private javax.swing.JButton btSEIS;
    private javax.swing.JButton btSIETE;
    private javax.swing.JButton btTRES;
    private javax.swing.JButton btUNO;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton16;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
